"use client";
import Link from "next/link";
import { useEffect, useState } from "react";
import "../actions.css";
type Product = { id: string; name: string; slug: string; category?: { name?: string } | string; brand?: string; status: "published" | "draft" };
export default function ProductsAdminPage() {
  const [products, setProducts] = useState<Product[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  useEffect(() => { fetch("/api/products?depth=1&sort=displayOrder&limit=100", { credentials: "include" }).then((r) => r.ok ? r.json() : Promise.reject(new Error("Unable to load products."))).then((data) => setProducts(data.docs || [])).catch((e: Error) => setError(e.message)).finally(() => setLoading(false)); }, []);
  async function removeProduct(id: string, name: string) { if (!window.confirm(`Delete “${name}”? This cannot be undone.`)) return; const response = await fetch(`/api/products/${id}`, { method: "DELETE", credentials: "include" }); if (!response.ok) { setError("Could not delete this product."); return; } setProducts((current) => current.filter((product) => product.id !== id)); }
  return <main className="cms-page"><div className="cms-page-heading"><div><span className="cms-kicker">Catalogue</span><h1>Products</h1><p>Manage the products available across the Rasana catalogue.</p></div><Link className="primary-button" href="/admin/products/new">+ Add product</Link></div><section className="panel cms-table-panel">{loading && <p className="cms-table-message">Loading products…</p>}{error && <p className="cms-table-message cms-table-error">{error}</p>}{!loading && !error && products.length === 0 && <p className="cms-table-message">No products yet. Add the first product to begin.</p>}{products.length > 0 && <div className="cms-data-table cms-product-table"><div className="cms-data-row cms-data-head"><span>Product</span><span>Category</span><span>Status</span><span>Brand</span><span>Actions</span></div>{products.map((product) => <div className="cms-data-row" key={product.id}><strong>{product.name}</strong><span>{typeof product.category === "object" ? product.category?.name || "—" : product.category || "—"}</span><span><i className={`cms-status-dot ${product.status}`} />{product.status}</span><span>{product.brand || "—"}</span><span className="cms-row-actions"><Link href={`/admin/products/${product.id}`}>Edit</Link><button type="button" onClick={() => removeProduct(product.id, product.name)}>Delete</button></span></div>)}</div>}</section></main>;
}
