"use client";
import Link from "next/link";
import { FormEvent, useState } from "react";

export function PartnerForm({ title, description, onSubmit, error, saving, brand = {} }: { title: string; description: string; onSubmit: (event: FormEvent<HTMLFormElement>) => void; error: string; saving: boolean; brand?: Record<string, unknown> }) {
  const [logoUrl, setLogoUrl] = useState(String(brand.logoUrl || ""));
  const [uploading, setUploading] = useState(false);
  const [uploadError, setUploadError] = useState("");
  async function uploadLogo(file?: File) { if (!file) return; setUploading(true); setUploadError(""); const response = await fetch(`/api/avatar/upload?filename=${encodeURIComponent(file.name)}`, { method: "POST", body: file, credentials: "include" }); if (!response.ok) { setUploadError("Logo upload failed. Check your Vercel Blob configuration."); setUploading(false); return; } const blob = await response.json(); setLogoUrl(blob.url); setUploading(false); }
  return <main className="cms-page"><div className="cms-page-heading"><div><Link className="cms-back-link" href="/admin/partners">← Partners</Link><h1>{title}</h1><p>{description}</p></div></div><form className="panel cms-form cms-form-wide" onSubmit={onSubmit}><input type="hidden" name="logoUrl" value={logoUrl} /><div className="cms-form-grid"><label>Partner name<input name="name" defaultValue={String(brand.name || "")} required /></label><label>Slug<input name="slug" defaultValue={String(brand.slug || "")} required /></label></div><label>Partner logo<input type="file" accept="image/jpeg,image/png,image/webp" onChange={(event) => uploadLogo(event.target.files?.[0])} />{uploading && <small>Uploading logo…</small>}{uploadError && <small className="cms-table-error">{uploadError}</small>}{logoUrl && <img src={logoUrl} alt="Partner logo preview" style={{ maxWidth: 220, maxHeight: 80, objectFit: "contain", marginTop: 8 }} />}</label><label>Home description<textarea name="homeDescription" rows={4} defaultValue={String(brand.homeDescription || "")} /></label><label>Full description<textarea name="fullDescription" rows={7} defaultValue={String(brand.fullDescription || "")} /></label><div className="cms-form-grid"><label>Website<input name="website" defaultValue={String(brand.website || "")} /></label><label>Display order<input name="displayOrder" type="number" defaultValue={String(brand.displayOrder || 0)} /></label></div><label>Status<select name="status" defaultValue={String(brand.status || "draft")}><option value="published">Published</option><option value="draft">Draft</option></select></label>{error && <p className="cms-table-error">{error}</p>}<div className="cms-form-actions"><Link className="secondary-button" href="/admin/partners">Cancel</Link><button className="primary-button" type="submit" disabled={saving || uploading}>{saving ? "Saving…" : "Save partner"}</button></div></form></main>;
}
